### ISSUE TITLE
Setup `chartpress` for automatic image builds and helm chart publishing

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/unnamed-thingity-thing#12]
We want to automatically build deployment artifacts out of this repository and publish them.

- The Docker Image to quay.io
- The helm chart to a GitHub pages setup for this purpose

[chartpress](https://github.com/jupyterhub/chartpress) was created for this purpose, so let's use it here.

## Resources

[cryptnono](https://github.com/cryptnono/cryptnono) is the last place I setup chartpress, and it may be a useful reference. But all the JupyterHub related helm charts as well as binderhub-service use chartpress, so config may be stolen from any of them.

## Definition of done

- Image built and pushed to a public repository on `quay.io`. This can be under the 2i2c org for now.
- There's a helm repository published to https://2i2c-org.github.io/unnamed-thingity-thingy/index.yaml (similar to cryptnono.github.io/cryptnono/index.yaml) that can be used with `helm repo add`
- Without a local install, someone doing `helm install` with the published repo with the default settings is able to get a working web interface

**Comment by GeorgianaElena** [comment]
Helm chart published at https://2i2c.org/unnamed-thingity-thing/
Docker image available at https://quay.io/repository/2i2c/unnamed?tab=tags
