### ISSUE TITLE
Limit max number of concurrent evaluation containers that can run in one go

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/unnamed-thingity-thing#130]
Since evaluation scripts can now run for tens of minutes, we should make sure we limit how many of them can run concurrently. Otherwise, the entire server will grind to a halt as everything tries to run concurrently!

This should be set up via a django setting.

## Definition of done

- [ ] A django setting that sets the maximum concurrent number of running evaluations is respected

**Comment by GeorgianaElena** [comment]
@yuvipanda, I was thinking to take this up next. Is that ok?

**Comment by yuvipanda** [comment]
@GeorgianaElena yes you can!
