### ISSUE TITLE
Add a Django setting to add footers to all pages

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/unnamed-thingity-thing#14]
We want to be able to add js snippets to the footer of each page. This is primarily helpful for handling analytics

## Resources

A context processor is probably needed to inject this info into all pages without needing to explicitly pass it for all template renders manually. We already have a template context processor, this can be added on.

```[tasklist]
- [ ] Add a new setting named that will hold the desired raw HTML/JS content to settings.py (or yaml)
- [ ] Follow https://docs.djangoproject.com/en/5.1/ref/templates/api/#writing-your-own-context-processors and add a context processor that will render this setting to all of the pages
- [ ] Add this setting to `page.html` and make sure it gets rendered
```

## Definition of done

- [ ] A Django setting that provides raw html to be embedded at the end of each page

**Comment by GeorgianaElena** [comment]
This was also refined
