### ISSUE TITLE
Update the helm-chart to support running the evaluator

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/unnamed-thingity-thing#25]
The evaluator command starts a process that continuously monitors and manages the evaluation of submissions using Docker containers. It creates evaluation objects, starts evaluations, and check the status of running evaluations.

We need to deploy this alongside our application to handle submissions and run scripts to evaluate each of them.

### Definition of Done

- [x] create a new side-car container that runs `python manage.py evaluator`
- [x] https://github.com/2i2c-org/unnamed-thingity-thing/issues/112
- [x] ensure this sidecar can access a docker daemon so it can pull the docker image and can create new docker containers. Decide between:
    - ~mounting the docker socket of the node into the sidecar container~ (nodes don't run docker anymore in k8s https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/)
    - do something similar to what binderhub-service does, which is to deploy a daemon set that starts a new dockerd daemon on all nodes and then mount that into the sidecar container
- [ ] check that deploying this works

**Comment by GeorgianaElena** [comment]
The evaluator is still not able to create containers for evaluating submissions. On a local deployment, I'm seeing the following error:
```
Container: {'Status': 'exited', 'Running': False, 'Paused': False, 'Restarting': False, 'OOMKilled': False, 'Dead': False, 'Pid': 0, 'ExitCode': 1, 'Error': '', 'StartedAt': '2024-10-08T13:23:44.33408293Z', 'FinishedAt': '2024-10-08T13:23:44.543285513Z'}
```

Tomorrow I plan to enable logging from the evaluator as atm we can only see `DEBUG` logs from the database and that's it. Get that into the staging deployment and figure out why new containers don't get created (locally I'm seeing the `OOMKilled` reason).

**Comment by yuvipanda** [comment]
This works since #118!
