### ISSUE TITLE
Use `djlint` to pre-commit our django templates

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/unnamed-thingity-thing#27]
Currently they are being linted and autoformatted as HTML, leading to errors like this:

<img width="1153" alt="image" src="https://github.com/user-attachments/assets/381e1d50-bd6a-428d-8cd5-43710b776da7">

Instead, djlint should be used for all files inside the templates directory: https://www.djlint.com/docs/integrations/

```[tasklist]
- [ ] Update  `.pre-commit-config.yaml` to run the `djlint` hook on all the files in the templates directory
- [ ] Validate that it works
```
### Definition of Done
- [ ] there is a pre-commit hook that runs djlint
- [ ] errors are not rendered as html anymore

**Comment by GeorgianaElena** [comment]
Refined
