### ISSUE TITLE
Update technical content

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/unnamed-thingity-thing#96]
### Context

There are continuous updates to the technical content of the website that are managed through the admin interface. This card represents this work until we can hand it off to the community

### Definition of done

- [ ] Update site content in the short term while we prepare for the launch
- [ ] Guide community on how to use the admin interface to update site content independently

**Comment by consideRatio** [comment]
@jnywong I made the assumption this is to be assigned to you as it was you who moved it into "in progress"

**Comment by jnywong** [comment]
I'm closing this as won't do since the challenge launch has been delayed to Nov and documentation efforts are captured in issues elsewhere.
